# Generated by Django 5.0.6 on 2024-06-21 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0003_remove_customuser_activation_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('etudiant', 'Étudiant'), ('superviseur', 'Superviseur'), ('membre_jury', 'Membre du jury')], default='etudiant', max_length=15),
        ),
    ]
