# Generated by Django 5.0.6 on 2024-06-21 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0004_alter_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='classe',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='filiere',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
