# Generated by Django 5.0.6 on 2024-06-21 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0006_alter_customuser_classe_alter_customuser_filiere'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='classe',
            field=models.CharField(blank=True, choices=[('3A', 'Classe 3A'), ('3B', 'Classe 3B'), ('3C', 'Classe 3C')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='filiere',
            field=models.CharField(blank=True, choices=[('cf', 'CF'), ('grh', 'GRH'), ('ad', 'AD'), ('cdm', 'CDM'), ('ge', 'GE'), ('ma', 'MA'), ('rgl', 'RGL')], max_length=50, null=True),
        ),
    ]
