# Generated by Django 5.0.6 on 2024-06-14 11:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soutenance_api', '0002_rename_titre_soutenance_title'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='soutenance',
            name='superviseur',
            field=models.ForeignKey(limit_choices_to={'role': 'supervisor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='soutenance',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
