# Generated by Django 5.0.6 on 2024-06-16 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soutenance_api', '0004_soutenance_etudiant_alter_soutenance_superviseur'),
    ]

    operations = [
        migrations.AddField(
            model_name='soutenance',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='pdfs/'),
        ),
    ]
