# Generated by Django 5.0.6 on 2024-06-22 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soutenance_api', '0007_soutenance_membres_jury'),
    ]

    operations = [
        migrations.AddField(
            model_name='soutenance',
            name='heure',
            field=models.TimeField(default='00:00:00'),
        ),
    ]
